logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.newspenguin.com%2Fnews%2FarticleView.html%3Fidxno%3D2412&psig=AOvVaw1M8azcOQfdO0GWqOiSxW2S&ust=1742072248070000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJDHsP66iowDFQAAAAAdAAAAABAE
title: Hanhee's Bioinformatics Course
theme: jekyll-theme-minimal
